name: pickride
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.3.0
  geocoding: ^3.0.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0  
  supabase_flutter: ^2.8.0
  shared_preferences: ^2.0.10  
  path_provider: ^2.0.16
  dotenv: ^4.2.0
  email_validator: ^2.1.17
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:   
    - .env